namespace ProductManagement;

public class ProductUI
{
    private readonly IProductStore _store;
    private readonly ProductValidator _validator;

    public ProductUI(IProductStore store)
    {
        _store = store;
        _validator = new ProductValidator(store);
    }

    public void InteractiveAdd()
    {
        var product = EnterProduct();

        if (!ValidateProduct(product))
        {
            Console.WriteLine("Product not added due to validation errors.\n");
            Console.WriteLine("Product details:");
            Console.WriteLine(product.ToString());
            return;
        }
        _store.Add(product);
        Console.WriteLine("Product added successfully.\n");
    }

    public void DisplayProducts()
    {
        var products = _store.GetAll();
        if (products.Count == 0)
        {
            Console.WriteLine("No products available.");
            return;
        }
        // Column widths
        const int idWidth = 4;
        const int codeWidth = 12;
        const int nameWidth = 20;
        const int descWidth = 60;
        const int priceWidth = 12;
        const int qtyWidth = 8;

        int totalWidth = idWidth + codeWidth + nameWidth + descWidth + priceWidth + qtyWidth + (5 * 1); // spaces between columns

        Console.WriteLine();
        Console.WriteLine("--- Product List ---");

        // Header
        Console.WriteLine(
            "ID".PadRight(idWidth) + " " +
            "Code".PadRight(codeWidth) + " " +
            "Name".PadRight(nameWidth) + " " +
            "Description".PadRight(descWidth) + " " +
            "Price".PadLeft(priceWidth) + " " +
            "Quantity".PadLeft(qtyWidth)
        );

        Console.WriteLine(new string('-', totalWidth));

        foreach (var product in products)
        {
            string desc = product.Description ?? string.Empty;

            // Truncate for display to fit the column, add ellipsis when truncated
            string descDisplay = desc.Length > descWidth ? string.Concat(desc.AsSpan(0, descWidth - 3), "...") : desc;

            string line =
                product.ProductId.ToString().PadRight(idWidth) + " " +
                (product.ProductCode ?? string.Empty).PadRight(codeWidth) + " " +
                (product.Name ?? string.Empty).PadRight(nameWidth) + " " +
                descDisplay.PadRight(descWidth) + " " +
                product.Price.ToString("C").PadLeft(priceWidth) + " " +
                product.Quantity.ToString().PadLeft(qtyWidth);

            Console.WriteLine(line);
        }
    }


    private Product EnterProduct()
    {
        string code = ReadRequired("Product Code (required): ");

        // Name is required and not empty or whitespace checked by the ReadRequired method, so we can skip the validation for it in the ProductValidator.
        // => validateName in ProductValidator is extra (always valid names). However, we can keep it for consistency with other fields
        string name = ReadRequired("Name (required): ");
        string description = ReadOptional("Description (optional): ");
        decimal price = ReadDecimal("Price (required): ");
        int quantity = ReadInt("Quantity (required): ");

        // productId is auto-generated by the store
        return new Product(code, name, description, price, quantity);

    }

    private bool ValidateProduct(Product product)
    {
        var errors = _validator.ValidateAll(product);

        if (errors.Count > 0)
        {
            Console.WriteLine("Product could not be added. Please fix the following:");
            foreach (var error in errors)
                Console.WriteLine($"  - {error}");
            return false;
        }
        return true;
    }
    private static string ReadRequired(string prompt)
    {
        string? input;
        do
        {
            Console.Write(prompt);
            input = Console.ReadLine();
        } while (string.IsNullOrWhiteSpace(input));

        // At this point, input is guaranteed non-null and non-whitespace
        return input!;
    }

    private static string ReadOptional(string prompt)
    {
        Console.Write(prompt);
        return Console.ReadLine() ?? "";
    }

    private static decimal ReadDecimal(string prompt)
    {
        decimal value;
        while (true)
        {
            var input = ReadRequired(prompt);
            if (decimal.TryParse(input, out value))
            {
                if (value > 0)
                {
                    return value;
                }
                Console.WriteLine("Price must be greater than 0. Try again :)");

            }
            else Console.WriteLine("Invalid Price. Try again with a valid decimal number :)");
        }
    }

    private static int ReadInt(string prompt)
    {
        int value;
        while (true)
        {
            var input = ReadRequired(prompt);
            if (int.TryParse(input, out value))
            {
                if (value >= 0)
                    return value;
                Console.WriteLine("Quantity must be zero or positive. Try again :)");
            }
            else
                Console.WriteLine("Quantity must be an integer Number. Try again :)");
        }
    }

    public static void DisplayMenu()
    {
        Console.WriteLine("--------------------");
        Console.WriteLine("Welcome to the Product Management System!");
        Console.WriteLine("1. Add Product");
        Console.WriteLine("2. Display Products");
        Console.WriteLine("3. Exit");
    }

}